# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.stepGlobal <- function(data, pastInfo, threshold, quantiles) {
    .Call(`_changepoint_np_new_NUNCstepGlobal`, data, pastInfo, threshold, quantiles)
}

.stepLocal <- function(data, threshold, quantiles, grid) {
    .Call(`_changepoint_np_new_NUNCstepLocal`, data, threshold, quantiles, grid)
}

.NUNCGlobal <- function(dataGen, w, beta, K) {
    .Call(`_changepoint_np_new_NUNCGlobal`, dataGen, w, beta, K)
}

.NUNCLocal <- function(dataGen, w, beta, K, grid) {
    .Call(`_changepoint_np_new_NUNCLocal`, dataGen, w, beta, K, grid)
}

.NUNCsemiParam <- function(dataGen, w, beta, quantiles) {
    .Call(`_changepoint_np_new_NUNCSemiParametric`, dataGen, w, beta, quantiles)
}

.NUNCGlobalOffline <- function(data, w, beta, K) {
    .Call(`_changepoint_np_new_NUNCGlobalOffline`, data, w, beta, K)
}

.NUNCLocalOffline <- function(data, w, beta, K, grid) {
    .Call(`_changepoint_np_new_NUNCLocalOffline`, data, w, beta, K, grid)
}

.NUNCsemiParamOffline <- function(data, w, beta, quantiles) {
    .Call(`_changepoint_np_new_NUNCsemiParametricOffline`, data, w, beta, quantiles)
}

rcpp_pelt <- function(sumstats, beta, nquantiles) {
    .Call(`_changepoint_np_new_rcpp_pelt`, sumstats, beta, nquantiles)
}

